[package]
name = "reproduce-375"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = { version = "0.4.0", features = ["language"], default-features = false }
tokio = { version = "1.44.2", features = ["full"] }
